---
- hosts:  "{{ hosts }}"
  become:  true
  tasks:
    - name:
      group:
        name:  "{{ item }}"
      with_items:
        - web
        - BBDD
        - SO       
    - name:  creamos varios usuarios pepe
      user:
        name:  "{{ item.username }}"
        group:  "{{ item.groupname }}"
        shell:  "/bin/bash"
        comment:  "usuario creado automatico por ansible"
        state:  present
      with_items:
        - { username: 'rlujan', groupname: 'web' }
        - { username: 'jnavarr5', groupname: 'BBDD' }
        - { username: 'msanch40', groupname: 'SO' }
